apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lzbi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lzbi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lzbi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lzbi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lzbi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-slxs-tenant/rhtap-demo-app/hacbs-test-project-lzbi@sha256:5d1df77d59921098a3a8932a36b4db8b54313b8b228ca611af4f5ceeb4c10442
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
